# Generated by Django 3.1.7 on 2021-04-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_file',
            name='file',
            field=models.FileField(upload_to='csv/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='uploaded_file',
            name='uploaded_at',
            field=models.DateTimeField(verbose_name='Дата добавления'),
        ),
    ]
