# Generated by Django 3.1.7 on 2021-04-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210403_0914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploaded_file',
            options={'verbose_name': 'Загруженный файл', 'verbose_name_plural': 'Загруженные файлы'},
        ),
        migrations.AlterField(
            model_name='uploaded_file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
