# Generated by Django 3.1.7 on 2021-04-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210403_1253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uploaded_file',
            new_name='UploadedFile',
        ),
    ]
